[package]
name = "napi-example"
version = "0.1.0"
authors = ["Alexey Orlenko <eaglexrlnk@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
napi = { path = "../crates/napi" }
napi-codegen = { path = "../crates/napi-codegen" }
