[package]
name = "napi-example"
version = "0.1.0"
authors = ["Alexey Orlenko <eaglexrlnk@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
napi = { path = "../napi" }
napi-derive = { path = "../napi-derive" }
