[package]
name = "napi-example"
version = "0.1.0"
authors = ["Alexey Orlenko <eaglexrlnk@gmail.com>"]
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
napi = { version = "0.1.1", path = "../napi" }
napi-derive = { version = "0.1.1", path = "../napi-derive" }
