language: rust

rust: nightly

cache: cargo

install:
  - cargo install cargo-update || true
  - cargo install rustfmt-nightly || true
  - cargo install clippy || true
  - cargo install-update --all

  - rustfmt --version
  - cargo clippy --version

script:
  - export RUST_BACKTRACE=1
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(rustc --print sysroot)/lib

  - cargo fmt --all -- --write-mode diff
  - cargo build --all --verbose
  - cargo clippy --all --verbose
  - cargo test --all --verbose
