language: rust

rust: nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

install:
  - cargo install cargo-update || true
  - cargo install rustfmt-nightly || true
  - cargo install clippy || true
  - cargo install-update --all

  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(rustc --print sysroot)/lib

  - rustfmt --version
  - cargo clippy --version

script:
  - cargo fmt --all -- --write-mode diff
  - cargo build --all
  - cargo clippy --all
  - cargo test --all
