language: rust

rust: nightly

cache: cargo

env:
  global:
    - RUST_BACKTRACE=1

install:
  - which cargo-install-update || cargo install cargo-update
  - which rustfmt || cargo install rustfmt-nightly
  - which cargo-clippy || cargo install clippy
  - cargo install-update --all

  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(rustc --print sysroot)/lib

  - rustfmt --version
  - cargo clippy --version

script:
  - cargo fmt --all -- --write-mode diff
  - cargo build --all
  - cargo clippy --all
  - cargo test --all
